// Package shared provides common types and interfaces for MediSync AI agents.
//
// This file defines the core types used across all agents including request/response
// structures, confidence scoring, visualization specifications, and error types.
package shared

import (
	"time"

	"github.com/google/uuid"
)

// ============================================================================
// Query Processing Types
// ============================================================================

// QueryContext represents context from a previous query for multi-turn conversations.
type QueryContext struct {
	Query         string `json:"query"`
	ResultSummary string `json:"result_summary"`
	SQL           string `json:"sql,omitempty"`
}

// ProcessedQuery represents the result of processing a natural language query.
type ProcessedQuery struct {
	// OriginalQuery is the raw user input
	OriginalQuery string `json:"original_query"`
	// NormalizedQuery is the query after terminology normalization
	NormalizedQuery string `json:"normalized_query"`
	// DetectedLocale is the detected language ("en" or "ar")
	DetectedLocale string `json:"detected_locale"`
	// DetectedIntent is the classified intent (trend, comparison, breakdown, kpi, table)
	DetectedIntent string `json:"detected_intent"`
	// TranslatedQuery is the English translation if original was Arabic
	TranslatedQuery string `json:"translated_query,omitempty"`
	// TerminologyMappings contains domain term mappings applied
	TerminologyMappings []TermMapping `json:"terminology_mappings,omitempty"`
}

// TermMapping represents a domain terminology mapping.
type TermMapping struct {
	Original   string `json:"original"`
	MappedTo   string `json:"mapped_to"`
	EntityType string `json:"entity_type,omitempty"` // "table", "column", "value"
}

// ============================================================================
// SQL Generation Types
// ============================================================================

// GeneratedSQL represents SQL generated by the Text-to-SQL agent.
type GeneratedSQL struct {
	SQL           string                 `json:"sql"`
	IsParameterized bool                 `json:"is_parameterized"`
	Parameters    map[string]interface{} `json:"parameters,omitempty"`
	TablesUsed    []string               `json:"tables_used"`
	ColumnsUsed   []string               `json:"columns_used"`
	Confidence    float64                `json:"confidence"` // 0-100
	Explanation   string                 `json:"explanation,omitempty"`
}

// SQLValidationResult represents the result of SQL validation.
type SQLValidationResult struct {
	IsValid       bool     `json:"is_valid"`
	Errors        []string `json:"errors,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
	SanitizedSQL  string   `json:"sanitized_sql,omitempty"`
	BlockedReason string   `json:"blocked_reason,omitempty"`
}

// ============================================================================
// Query Result Types
// ============================================================================

// QueryResult represents the result of executing a SQL query.
type QueryResult struct {
	Columns []ColumnMeta               `json:"columns"`
	Rows    []map[string]interface{}   `json:"rows"`
	RowCount int                       `json:"row_count"`
	ExecutionTimeMs int64              `json:"execution_time_ms"`
	Metadata map[string]interface{}    `json:"metadata,omitempty"`
}

// ColumnMeta represents metadata about a result column.
type ColumnMeta struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Nullable bool   `json:"nullable"`
}

// ============================================================================
// Visualization Types
// ============================================================================

// ChartType defines the supported visualization types.
type ChartType string

const (
	ChartTypeLineChart    ChartType = "lineChart"
	ChartTypeBarChart     ChartType = "barChart"
	ChartTypePieChart     ChartType = "pieChart"
	ChartTypeKPICard      ChartType = "kpiCard"
	ChartTypeDataTable    ChartType = "dataTable"
	ChartTypeScatterChart ChartType = "scatterChart"
)

// VisualizationSpec represents a visualization recommendation.
type VisualizationSpec struct {
	ChartType     ChartType            `json:"chart_type"`
	Title         string               `json:"title"`
	TitleAR       string               `json:"title_ar,omitempty"`
	Subtitle      string               `json:"subtitle,omitempty"`
	XAxis         *AxisSpec            `json:"x_axis,omitempty"`
	YAxis         *AxisSpec            `json:"y_axis,omitempty"`
	Series        []SeriesSpec         `json:"series,omitempty"`
	Confidence    float64              `json:"confidence"`
	Reasoning     string               `json:"reasoning,omitempty"`
	Alternatives  []ChartType          `json:"alternatives,omitempty"`
}

// AxisSpec represents an axis specification for charts.
type AxisSpec struct {
	Label    string `json:"label"`
	LabelAR  string `json:"label_ar,omitempty"`
	Field    string `json:"field"`
	Type     string `json:"type"` // "category", "value", "time"
	Format   string `json:"format,omitempty"` // Number/date format
}

// SeriesSpec represents a data series specification.
type SeriesSpec struct {
	Name    string        `json:"name"`
	NameAR  string        `json:"name_ar,omitempty"`
	Field   string        `json:"field"`
	Type    string        `json:"type"` // "line", "bar", "scatter"
	Color   string        `json:"color,omitempty"`
	Values  []interface{} `json:"values,omitempty"`
}

// ============================================================================
// Confidence Scoring Types
// ============================================================================

// ConfidenceScore represents a detailed confidence assessment.
type ConfidenceScore struct {
	Overall       float64              `json:"overall"` // 0-100
	SQLConfidence float64              `json:"sql_confidence"`
	IntentConfidence float64           `json:"intent_confidence"`
	DataConfidence float64             `json:"data_confidence"`
	VisualizationConfidence float64    `json:"visualization_confidence"`
	Factors       []ConfidenceFactor   `json:"factors,omitempty"`
	NeedsClarification bool            `json:"needs_clarification"`
	ClarificationReason string         `json:"clarification_reason,omitempty"`
}

// ConfidenceFactor represents a factor contributing to the confidence score.
type ConfidenceFactor struct {
	Name        string  `json:"name"`
	Score       float64 `json:"score"`
	Weight      float64 `json:"weight"`
	Description string  `json:"description,omitempty"`
}

// ============================================================================
// Hallucination Guard Types
// ============================================================================

// HallucinationCheckResult represents the result of hallucination detection.
type HallucinationCheckResult struct {
	IsSafe              bool               `json:"is_safe"`
	RiskScore           float64            `json:"risk_score"` // 0-100, lower is safer
	DetectedIssues      []HallucinationIssue `json:"detected_issues,omitempty"`
	SchemaAlignment     float64            `json:"schema_alignment"` // 0-100
	DataConsistency     float64            `json:"data_consistency"` // 0-100
	Recommendation      string             `json:"recommendation,omitempty"`
}

// HallucinationIssue represents a detected hallucination issue.
type HallucinationIssue struct {
	Type        string `json:"type"` // "fabricated_table", "fabricated_column", "inconsistent_data"
	Description string `json:"description"`
	Severity    string `json:"severity"` // "low", "medium", "high"
	Location    string `json:"location,omitempty"` // SQL location or data reference
}

// ============================================================================
// Language Detection Types
// ============================================================================

// LanguageDetectionResult represents the result of language detection.
type LanguageDetectionResult struct {
	DetectedLanguage string  `json:"detected_language"` // "en" or "ar"
	Confidence       float64 `json:"confidence"`
	IsMixed          bool    `json:"is_mixed"`
	PrimaryScript    string  `json:"primary_script"` // "latin", "arabic"
}

// TranslationResult represents the result of query translation.
type TranslationResult struct {
	OriginalText   string  `json:"original_text"`
	TranslatedText string  `json:"translated_text"`
	SourceLanguage string  `json:"source_language"`
	TargetLanguage string  `json:"target_language"`
	Confidence     float64 `json:"confidence"`
}

// ============================================================================
// Localized Formatting Types
// ============================================================================

// FormattedValue represents a value formatted for a specific locale.
type FormattedValue struct {
	Raw        interface{} `json:"raw"`
	Formatted  string      `json:"formatted"`
	Locale     string      `json:"locale"`
	Type       string      `json:"type"` // "number", "currency", "date", "percent"
}

// LocaleConfig holds locale-specific formatting configuration.
type LocaleConfig struct {
	Locale         string `json:"locale"`
	CurrencySymbol string `json:"currency_symbol"`
	CurrencyCode   string `json:"currency_code"`
	DateFormat     string `json:"date_format"`
	TimeFormat     string `json:"time_format"`
	NumberFormat   string `json:"number_format"` // "en-IN", "en-US", etc.
	Direction      string `json:"direction"` // "ltr" or "rtl"
	CalendarSystem string `json:"calendar_system"` // "gregorian", "islamic"
}

// ============================================================================
// Event Types (for SSE streaming)
// ============================================================================

// EventType defines the types of Server-Sent Events.
type EventType string

const (
	EventTypeThinking      EventType = "thinking"
	EventTypeSQLPreview    EventType = "sql_preview"
	EventTypeResult        EventType = "result"
	EventTypeError         EventType = "error"
	EventTypeClarification EventType = "clarification"
)

// SSEEvent represents a Server-Sent Event.
type SSEEvent struct {
	Type        EventType           `json:"type"`
	Message     string              `json:"message,omitempty"`
	SQL         string              `json:"sql,omitempty"`
	ChartType   ChartType           `json:"chart_type,omitempty"`
	Data        interface{}         `json:"data,omitempty"`
	Confidence  float64             `json:"confidence,omitempty"`
	Options     []string            `json:"options,omitempty"`
	Timestamp   time.Time           `json:"timestamp"`
}

// ============================================================================
// Agent Pipeline Types
// ============================================================================

// QueryPipelineResult represents the complete result of query processing.
type QueryPipelineResult struct {
	SessionID        string                `json:"session_id"`
	QueryID          uuid.UUID             `json:"query_id"`
	Query            string                `json:"query"`
	ProcessedQuery   *ProcessedQuery       `json:"processed_query,omitempty"`
	SQL              string                `json:"sql"`
	SQLConfidence    float64               `json:"sql_confidence"`
	Result           *QueryResult          `json:"result,omitempty"`
	Visualization    *VisualizationSpec    `json:"visualization,omitempty"`
	Confidence       *ConfidenceScore      `json:"confidence"`
	Events           []SSEEvent            `json:"events"`
	Locale           string                `json:"locale"`
	FormattedData    interface{}           `json:"formatted_data,omitempty"`
	ProcessingTimeMs int64                 `json:"processing_time_ms"`
	CreatedAt        time.Time             `json:"created_at"`
}

// AgentError represents an error from an agent.
type AgentError struct {
	AgentID     string `json:"agent_id"`
	Code        string `json:"code"`
	Message     string `json:"message"`
	Confidence  float64 `json:"confidence,omitempty"`
	Suggestion  string `json:"suggestion,omitempty"`
	Retryable   bool   `json:"retryable"`
}

// Error implements the error interface.
func (e *AgentError) Error() string {
	return e.Message
}

// ============================================================================
// Agent Health Types
// ============================================================================

// AgentStatus defines the health status of an agent.
type AgentStatus string

const (
	AgentStatusHealthy   AgentStatus = "healthy"
	AgentStatusDegraded  AgentStatus = "degraded"
	AgentStatusUnhealthy AgentStatus = "unhealthy"
)

// LLMProviderStatus defines the status of the LLM provider.
type LLMProviderStatus string

const (
	LLMStatusConnected    LLMProviderStatus = "connected"
	LLMStatusDisconnected LLMProviderStatus = "disconnected"
	LLMStatusRateLimited  LLMProviderStatus = "rate_limited"
)

// AgentHealth represents the health status of a single agent.
type AgentHealth struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	Status          AgentStatus       `json:"status"`
	LastCheck       time.Time         `json:"last_check"`
	ResponseTimeMs  int64             `json:"response_time_ms,omitempty"`
	ErrorMessage    string            `json:"error_message,omitempty"`
	Metadata        map[string]string `json:"metadata,omitempty"`
}

// LLMProviderHealth represents the health of the LLM provider.
type LLMProviderHealth struct {
	Name          string             `json:"name,omitempty"`
	Model         string             `json:"model,omitempty"`
	Status        LLMProviderStatus  `json:"status,omitempty"`
	ResponseTimeMs int64             `json:"response_time_ms,omitempty"`
	ErrorMessage  string             `json:"error_message,omitempty"`
}

// AgentsHealthResponse represents the response for the agent health endpoint.
type AgentsHealthResponse struct {
	Status       string               `json:"status"`
	Timestamp    time.Time            `json:"timestamp"`
	Agents       []AgentHealth        `json:"agents"`
	LLMProvider  *LLMProviderHealth   `json:"llm_provider,omitempty"`
	Dependencies map[string]string    `json:"dependencies,omitempty"`
}
