import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { PinnedChart } from '../../services/api';

interface ChartPinDialogProps {
  onClose: () => void;
  onPin: (chart: Partial<PinnedChart>) => Promise<void>;
  locale: string;
}

export const ChartPinDialog: React.FC<ChartPinDialogProps> = ({
  onClose,
  onPin,
  locale,
}) => {
  const { t } = useTranslation('dashboard');

  const [title, setTitle] = useState('');
  const [naturalLanguageQuery, setNaturalLanguageQuery] = useState('');
  const [chartType, setChartType] = useState<'bar' | 'line' | 'pie' | 'table' | 'kpi'>('bar');
  const [refreshInterval, setRefreshInterval] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!title.trim() || !naturalLanguageQuery.trim()) {
      setError(t('dialog.requiredFields'));
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      await onPin({
        title,
        naturalLanguageQuery,
        chartType,
        refreshInterval,
        sqlQuery: '', // Will be generated by AI
        chartSpec: {},
        position: { row: 0, col: 0, size: 1 },
      });
    } catch {
      setError(t('dialog.pinError'));
      setIsSubmitting(false);
    }
  };

  const chartTypes = [
    { value: 'bar', label: t('chartTypes.bar') },
    { value: 'line', label: t('chartTypes.line') },
    { value: 'pie', label: t('chartTypes.pie') },
    { value: 'table', label: t('chartTypes.table') },
    { value: 'kpi', label: t('chartTypes.kpi') },
  ];

  const refreshOptions = [
    { value: 0, label: t('refreshOptions.manual') },
    { value: 5, label: t('refreshOptions.fiveMinutes') },
    { value: 15, label: t('refreshOptions.fifteenMinutes') },
    { value: 30, label: t('refreshOptions.thirtyMinutes') },
    { value: 60, label: t('refreshOptions.oneHour') },
    { value: 1440, label: t('refreshOptions.oneDay') },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div
        className="glass-elevated max-w-md w-full mx-4 overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="glass-subtle flex items-center justify-between px-6 py-4 border-b border-white/10 dark:border-gray-700">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
            {t('dialog.title')}
          </h2>
          <button
            onClick={onClose}
            className="glass-interactive p-1 rounded-lg"
          >
            <svg className="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="glass-subtle p-3 border-red-300 dark:border-red-500/30 text-red-600 dark:text-red-400 rounded-xl text-sm">
              {error}
            </div>
          )}

          {/* Title */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
              {t('dialog.titleLabel')} *
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={t('dialog.titlePlaceholder')}
              className="glass-interactive w-full px-3 py-2 rounded-xl text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              dir={locale === 'ar' ? 'rtl' : 'ltr'}
            />
          </div>

          {/* Natural Language Query */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
              {t('dialog.queryLabel')} *
            </label>
            <textarea
              value={naturalLanguageQuery}
              onChange={(e) => setNaturalLanguageQuery(e.target.value)}
              placeholder={t('dialog.queryPlaceholder')}
              rows={3}
              className="glass-interactive w-full px-3 py-2 rounded-xl text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
              dir={locale === 'ar' ? 'rtl' : 'ltr'}
            />
          </div>

          {/* Chart Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
              {t('dialog.chartTypeLabel')}
            </label>
            <div className="grid grid-cols-5 gap-2">
              {chartTypes.map((type) => (
                <button
                  key={type.value}
                  type="button"
                  onClick={() => setChartType(type.value as typeof chartType)}
                  className={`glass-interactive p-2 rounded-xl text-center text-sm transition-all ${
                    chartType === type.value
                      ? 'ring-2 ring-blue-500 bg-blue-50/50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400'
                      : 'text-slate-600 dark:text-gray-300'
                  }`}
                >
                  {type.label}
                </button>
              ))}
            </div>
          </div>

          {/* Refresh Interval */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1">
              {t('dialog.refreshLabel')}
            </label>
            <select
              value={refreshInterval}
              onChange={(e) => setRefreshInterval(Number(e.target.value))}
              className="glass-interactive w-full px-3 py-2 rounded-xl text-slate-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            >
              {refreshOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="glass-interactive px-4 py-2 text-slate-700 dark:text-gray-200 rounded-xl transition-all"
            >
              {t('dialog.cancel')}
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-4 py-2 bg-gradient-to-r from-blue-600 to-cyan-500 text-white rounded-xl hover:from-blue-500 hover:to-cyan-400 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-blue-500/25"
            >
              {isSubmitting ? t('dialog.pinning') : t('dialog.pin')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ChartPinDialog;
