import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LiquidGlassModal } from '../ui/LiquidGlassModal';
import { ButtonPrimary, ButtonSecondary } from '../ui/LiquidGlassButton';
import type { PinnedChart } from '../../services/api';

interface ChartPinDialogProps {
  onClose: () => void;
  onPin: (chart: Partial<PinnedChart>) => Promise<void>;
  locale: string;
}

export const ChartPinDialog: React.FC<ChartPinDialogProps> = ({
  onClose,
  onPin,
  locale,
}) => {
  const { t } = useTranslation('dashboard');

  const [title, setTitle] = useState('');
  const [naturalLanguageQuery, setNaturalLanguageQuery] = useState('');
  const [chartType, setChartType] = useState<'bar' | 'line' | 'pie' | 'table' | 'kpi'>('bar');
  const [refreshInterval, setRefreshInterval] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!title.trim() || !naturalLanguageQuery.trim()) {
      setError(t('dialog.requiredFields'));
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      await onPin({
        title,
        naturalLanguageQuery,
        chartType,
        refreshInterval,
        sqlQuery: '', // Will be generated by AI
        chartSpec: {},
        position: { row: 0, col: 0, size: 1 },
      });
    } catch {
      setError(t('dialog.pinError'));
      setIsSubmitting(false);
    }
  };

  const chartTypes = [
    { value: 'bar', label: t('chartTypes.bar') },
    { value: 'line', label: t('chartTypes.line') },
    { value: 'pie', label: t('chartTypes.pie') },
    { value: 'table', label: t('chartTypes.table') },
    { value: 'kpi', label: t('chartTypes.kpi') },
  ];

  const refreshOptions = [
    { value: 0, label: t('refreshOptions.manual') },
    { value: 5, label: t('refreshOptions.fiveMinutes') },
    { value: 15, label: t('refreshOptions.fifteenMinutes') },
    { value: 30, label: t('refreshOptions.thirtyMinutes') },
    { value: 60, label: t('refreshOptions.oneHour') },
    { value: 1440, label: t('refreshOptions.oneDay') },
  ];

  return (
    <LiquidGlassModal
      isOpen={true}
      onClose={onClose}
      title={t('dialog.title')}
      size="md"
      actions={
        <>
          <ButtonSecondary onClick={onClose}>
            {t('dialog.cancel')}
          </ButtonSecondary>
          <ButtonPrimary
            onClick={handleSubmit}
            disabled={isSubmitting}
          >
            {isSubmitting ? t('dialog.pinning') : t('dialog.pin')}
          </ButtonPrimary>
        </>
      }
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {error && (
          <div className="p-3 bg-red-500/20 text-red-400 rounded-lg text-sm border border-red-500/30">
            {error}
          </div>
        )}

        {/* Title */}
        <div>
          <label className="block text-sm font-medium liquid-text-primary mb-1">
            {t('dialog.titleLabel')} *
          </label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder={t('dialog.titlePlaceholder')}
            className="w-full px-3 py-2 border border-white/20 rounded-lg bg-white/10 text-white placeholder-white/50 focus:ring-2 focus:ring-blue-500/50 focus:border-transparent"
            dir={locale === 'ar' ? 'rtl' : 'ltr'}
          />
        </div>

        {/* Natural Language Query */}
        <div>
          <label className="block text-sm font-medium liquid-text-primary mb-1">
            {t('dialog.queryLabel')} *
          </label>
          <textarea
            value={naturalLanguageQuery}
            onChange={(e) => setNaturalLanguageQuery(e.target.value)}
            placeholder={t('dialog.queryPlaceholder')}
            rows={3}
            className="w-full px-3 py-2 border border-white/20 rounded-lg bg-white/10 text-white placeholder-white/50 focus:ring-2 focus:ring-blue-500/50 focus:border-transparent resize-none"
            dir={locale === 'ar' ? 'rtl' : 'ltr'}
          />
        </div>

        {/* Chart Type */}
        <div>
          <label className="block text-sm font-medium liquid-text-primary mb-1">
            {t('dialog.chartTypeLabel')}
          </label>
          <div className="grid grid-cols-5 gap-2">
            {chartTypes.map((type) => (
              <button
                key={type.value}
                type="button"
                onClick={() => setChartType(type.value as typeof chartType)}
                className={`p-2 rounded-lg border text-center text-sm transition-colors ${
                  chartType === type.value
                    ? 'border-blue-500/50 bg-blue-500/20 text-blue-400'
                    : 'border-white/20 hover:bg-white/10 liquid-text-primary'
                }`}
              >
                {type.label}
              </button>
            ))}
          </div>
        </div>

        {/* Refresh Interval */}
        <div>
          <label className="block text-sm font-medium liquid-text-primary mb-1">
            {t('dialog.refreshLabel')}
          </label>
          <select
            value={refreshInterval}
            onChange={(e) => setRefreshInterval(Number(e.target.value))}
            className="w-full px-3 py-2 border border-white/20 rounded-lg bg-white/10 text-white focus:ring-2 focus:ring-blue-500/50 focus:border-transparent"
          >
            {refreshOptions.map((option) => (
              <option key={option.value} value={option.value} className="bg-slate-900">
                {option.label}
              </option>
            ))}
          </select>
        </div>
      </form>
    </LiquidGlassModal>
  );
};

export default ChartPinDialog;
