package models

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// Validation status constants for SQL statements.
const (
	// ValidationStatusValid indicates the SQL statement passed validation
	ValidationStatusValid = "valid"
	// ValidationStatusBlocked indicates the SQL statement was blocked due to security concerns
	ValidationStatusBlocked = "blocked"
)

// Statement constraints
const (
	// MaxRetryCount is the maximum number of retry attempts for failed queries
	MaxRetryCount = 3
)

// ValidValidationStatuses contains all supported validation statuses.
var ValidValidationStatuses = map[string]bool{
	ValidationStatusValid:   true,
	ValidationStatusBlocked: true,
}

// SQLStatement represents a SQL query generated by the AI agent from a natural language query.
// It includes the SQL text, parameterization info, validation status, and retry tracking.
type SQLStatement struct {
	// ID is the unique identifier for the SQL statement
	ID uuid.UUID `json:"id" db:"id"`
	// QueryID references the parent natural language query
	QueryID uuid.UUID `json:"query_id" db:"query_id"`
	// SQLText contains the actual SQL query string
	SQLText string `json:"sql_text" db:"sql_text"`
	// IsParameterized indicates whether the query uses parameters
	IsParameterized bool `json:"is_parameterized" db:"is_parameterized"`
	// Parameters contains the parameter name-value pairs for parameterized queries
	Parameters map[string]any `json:"parameters" db:"parameters"`
	// ValidationStatus indicates whether the query passed or was blocked
	ValidationStatus string `json:"validation_status" db:"validation_status"`
	// BlockedReason contains the reason if the query was blocked
	BlockedReason string `json:"blocked_reason" db:"blocked_reason"`
	// RetryCount tracks how many times the query has been retried
	RetryCount int `json:"retry_count" db:"retry_count"`
	// CreatedAt is the timestamp when the statement was created
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Validate checks if the SQLStatement has valid field values.
// It ensures required fields are populated and status values are valid.
func (s *SQLStatement) Validate() error {
	if s.SQLText == "" {
		return errors.New("sql_text is required and cannot be empty")
	}

	if s.QueryID == uuid.Nil {
		return errors.New("query_id is required and cannot be empty")
	}

	if s.ValidationStatus != "" && !ValidValidationStatuses[s.ValidationStatus] {
		return fmt.Errorf("invalid validation_status '%s': must be one of 'valid' or 'blocked'", s.ValidationStatus)
	}

	if s.RetryCount < 0 {
		return errors.New("retry_count cannot be negative")
	}

	if s.RetryCount > MaxRetryCount {
		return fmt.Errorf("retry_count cannot exceed %d", MaxRetryCount)
	}

	return nil
}

// IsSELECT checks if the SQL statement is a SELECT query.
// It performs a case-insensitive check on the trimmed SQL text.
// This is critical for security - only SELECT queries should be executed
// by the AI agents using the medisync_readonly database role.
func (s *SQLStatement) IsSELECT() bool {
	trimmed := strings.TrimSpace(s.SQLText)
	upper := strings.ToUpper(trimmed)
	return strings.HasPrefix(upper, "SELECT")
}

// IncrementRetry increments the retry count by one.
// It returns an error if the maximum retry count has already been reached.
func (s *SQLStatement) IncrementRetry() error {
	if s.RetryCount >= MaxRetryCount {
		return fmt.Errorf("maximum retry count of %d has been reached", MaxRetryCount)
	}
	s.RetryCount++
	return nil
}

// Parameterize adds or updates parameters for the SQL statement.
// It also sets IsParameterized to true.
func (s *SQLStatement) Parameterize(params map[string]any) {
	if s.Parameters == nil {
		s.Parameters = make(map[string]any)
	}
	for k, v := range params {
		s.Parameters[k] = v
	}
	s.IsParameterized = true
}

// NewSQLStatement creates a new SQLStatement with the provided parameters.
// It generates a new UUID, initializes empty parameters, and sets the creation timestamp.
func NewSQLStatement(queryID uuid.UUID, sqlText string) *SQLStatement {
	return &SQLStatement{
		ID:               uuid.New(),
		QueryID:          queryID,
		SQLText:          sqlText,
		IsParameterized:  false,
		Parameters:       make(map[string]any),
		ValidationStatus: "",
		BlockedReason:    "",
		RetryCount:       0,
		CreatedAt:        time.Now(),
	}
}
